import {notFound} from 'next/navigation';
import {ArrowUpRight,Mail,Layers,Paintbrush,Leaf} from 'lucide-react';
import {info,origin,faqs} from '@/lib/content';
import {CTA} from '@/components/site-shell';
export async function generateMetadata({params}:{params:Promise<{page:string}>}){const{page}=await params;const title=info[page]?.title??({materials:'Materials & finishes',contact:'Contact PackifyBoxes'} as Record<string,string>)[page];return {title:title+' | PackifyBoxes',description:info[page]?.intro??'Explore your next custom packaging project with PackifyBoxes.',alternates:{canonical:origin+'/'+page}}}
export default async function Info({params}:{params:Promise<{page:string}>}){const{page}=await params;
if(page==='contact')return <main id="main"><section className="wrap page-intro"><div className="eyebrow">LET’S TALK PACKAGING</div><h1>Big idea?<br/><em>Start with hello.</em></h1><p>Questions about a box style, an upcoming launch or an existing inquiry? Get in touch and tell us what you need.</p></section><section className="wrap contact-grid section"><div className="contact-card"><Mail size={32}/><h2>Drop us a line.</h2><p>For product questions, samples and project conversations.</p><a className="text-link" href="mailto:contact@packifyboxes.com">contact@packifyboxes.com <ArrowUpRight size={18}/></a></div><div className="contact-card"><Layers size={32}/><h2>Have a project in mind?</h2><p>A few details help us understand your product and prepare a useful quote.</p><a className="btn" href="/quote">Build your packaging brief <ArrowUpRight size={18}/></a></div></section><section className="section wrap faq-section"><div><div className="eyebrow">A GOOD PLACE TO START</div><h2>Common questions.</h2></div><div className="faq-list">{faqs.slice(0,4).map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section></main>;
if(page==='materials')return <main id="main"><section className="wrap page-intro"><div className="eyebrow">THE DETAILS MAKE THE DIFFERENCE</div><h1>Feel the difference.<br/><em>Find your finish.</em></h1><p>Build the right combination of structure, surface and finishing. Availability and suitability are confirmed for your specific packaging.</p></section><section className="section wrap"><div className="section-head"><h2>Start with the foundation.</h2><a className="text-link" href="/guides/packaging-materials">Read the material guide <ArrowUpRight size={17}/></a></div><div className="guide-grid">{[['Paperboard','A versatile option for folding cartons, sleeves and retail presentation. Choose the grade around product weight and print requirements.'],['Corrugated board','A fluted construction to explore for mailers and shipping boxes. Match the grade and flute to the packed product and journey.'],['Wrapped rigid board','A substantial structure for gift sets and premium presentation. Consider the wrapped paper, insert and storage footprint.']].map(([t,d])=><div className="guide-card" key={t}><Layers size={30}/><h3>{t}</h3><p>{d}</p></div>)}</div><div className="section-head finishing-head"><h2>Then add your signature.</h2></div><div className="finishes">{[['Full-color printing','Build a consistent visual system with process print or specified spot colors.'],['Foil stamping','Give selected brand details a metallic accent. Confirm the foil, artwork and substrate together.'],['Emboss & deboss','Create raised or recessed detail for a tactile brand impression.'],['Matte & gloss','Explore coatings and laminates for the surface feel and appearance you need.'],['Spot UV','Contrast selected glossy details against the surrounding surface.'],['Inserts & sleeves','Organize a set, separate products and add another space for your story.']].map(([t,d])=><div key={t}><Paintbrush size={20}/><h3>{t}</h3><p>{d}</p></div>)}</div><aside className="eco-note"><Leaf size={32}/><div><h3>Make environmental claims specific.</h3><p>Ask for evidence of recycled content or certification for the chosen stock. Check how coatings, windows and inserts affect disposal. Material color alone does not establish an environmental benefit.</p></div></aside></section><CTA/></main>;
const c=info[page];if(!c)notFound();return <main id="main"><article className="wrap article"><div className="eyebrow">{page==='about'?'OUR STORY':'THE DETAILS'}</div><h1>{c.title}</h1><p className="lead">{c.intro}</p>{c.sections.map(([t,d])=><section key={t}><h2>{t}</h2><p>{d}</p></section>)}</article>{page==='about'&&<CTA/>}</main>}
