import {bindings,database} from '@/lib/db';
import {products,origin} from '@/lib/content';
const MAX_FILE=5*1024*1024,MAX_BODY=MAX_FILE+65536;
function failure(error:string,status=400){return Response.json({error},{status,headers:{'Cache-Control':'no-store'}})}
export async function POST(request:Request){
 const source=request.headers.get('origin');const url=new URL(request.url);const allowed=new Set([origin]);if(url.hostname==='localhost'||url.hostname==='127.0.0.1')allowed.add(url.origin);if(!source||!allowed.has(source))return failure('This request must come from the packaging quote form.',403);
 if(!request.headers.get('content-type')?.startsWith('multipart/form-data'))return failure('Please use the quote form.');
 if(Number(request.headers.get('content-length'))>MAX_BODY)return failure('Your reference file must be no larger than 5 MB.',413);
 let fileKey:string|null=null;let stored=false;
 try{
  const db=await database();const now=Date.now();const hour=Math.floor(now/3600000);const ip=request.headers.get('cf-connecting-ip')||'local';const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ip+':'+hour)))).map(v=>v.toString(16).padStart(2,'0')).join('');
  const rate=await db.prepare('INSERT INTO request_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(hash,now+3600000).first<{count:number}>();await db.prepare('DELETE FROM request_limits WHERE expires < ?').bind(now).run();if(!rate||rate.count>5)return failure('Too many requests. Please wait an hour or contact us by email.',429);
  if(!request.body)return failure('Your form is empty.');const reader=request.body.getReader();const chunks:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX_BODY){await reader.cancel();return failure('Your reference file must be no larger than 5 MB.',413)}chunks.push(value)}const payload=new Uint8Array(size);let offset=0;for(const part of chunks){payload.set(part,offset);offset+=part.byteLength}const data=await new Response(payload,{headers:{'Content-Type':request.headers.get('content-type')!}}).formData();
  const get=(key:string,max:number)=>{const val=data.get(key);if(typeof val!=='string')return '';if(val.length>max)throw new Error('Please shorten the '+key+' field.');return val.trim()};
  if(get('website',500))return failure('Unable to accept this request.');const elapsed=now-Number(get('started',20));if(!Number.isFinite(elapsed)||elapsed<2000||elapsed>86400000)return failure('Please refresh the page and complete the form again.');
  const name=get('name',100),email=get('email',200),product=get('product',80),quantity=Number(get('quantity',12)),destination=get('destination',180);if(!name||!/^\S+@\S+\.\S+$/.test(email)||!destination||!Number.isInteger(quantity)||quantity<1||quantity>10000000||!([...products.map(p=>p.slug),'not-sure']).includes(product)||get('consent',10)!=='yes')return failure('Please complete the required fields and privacy consent.');
  const details=JSON.stringify({dimensions:get('dimensions',100),material:get('material',100),printing:get('printing',180),destination,timing:get('timing',120),notes:get('notes',3000)});const company=get('company',120),phone=get('phone',40);const id='PB-'+crypto.randomUUID();const file=data.get('reference');let fileName:string|null=null;
  if(file instanceof File&&file.size){if(file.size>MAX_FILE)return failure('Your reference file must be no larger than 5 MB.',413);const bytes=new Uint8Array(await file.arrayBuffer());const pdf=bytes[0]===37&&bytes[1]===80&&bytes[2]===68&&bytes[3]===70&&bytes[4]===45;const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10;const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const type=pdf?'application/pdf':png?'image/png':jpg?'image/jpeg':'';const ext=pdf?'pdf':png?'png':'jpg';if(!type||type!==file.type||!(pdf?/\.pdf$/i:png?/\.png$/i:/\.jpe?g$/i).test(file.name))return failure('Use a valid PDF, PNG or JPEG reference file.');if(!bindings().FILES)return failure('File storage is temporarily unavailable. Try without an attachment.',503);fileKey='quote-references/'+id+'.'+ext;fileName=file.name.replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,120);await bindings().FILES.put(fileKey,bytes,{httpMetadata:{contentType:'application/octet-stream',contentDisposition:'attachment'}})}
  await db.prepare('INSERT INTO quotes (id,created_at,name,email,company,phone,product,quantity,details,file_key,file_name,consent_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,now,name,email,company,phone,product,quantity,details,fileKey,fileName,'2026-09-08').run();stored=true;
  return Response.json({reference:id},{status:201,headers:{'Cache-Control':'no-store'}});
 }catch(error){if(fileKey&&!stored){try{await bindings().FILES.delete(fileKey)}catch{}}if(error instanceof Error&&error.message.startsWith('Please shorten'))return failure(error.message);return failure('We could not save your request. Please try again or email contact@packifyboxes.com.',503)}
}
